# Generated by Django 5.2.17 on 2026-10-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="nom"),
                ),
                ("slug", models.SlugField(editable=False, max_length=170, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sport", "Sport"),
                            ("culture", "Culture & arts"),
                            ("social", "Social & solidarité"),
                            ("environnement", "Environnement"),
                            ("education", "Éducation & jeunesse"),
                            ("sante", "Santé"),
                            ("loisirs", "Loisirs"),
                            ("quartier", "Vie de quartier"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="domaine",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=200, verbose_name="description courte"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="présentation"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail de contact"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="site web")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="adresse"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="validée"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créée par",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrateur"), ("member", "Membre")],
                        default="member",
                        max_length=10,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("active", "Actif")],
                        default="pending",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="associations.association",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "adhésion",
                "ordering": ["association__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "association"), name="unique_membership"
                    )
                ],
            },
        ),
    ]
