# Generated by Django 5.2.17 on 2026-10-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("associations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sport", "Sport"),
                            ("culture", "Culture & arts"),
                            ("social", "Social & solidarité"),
                            ("environnement", "Environnement"),
                            ("education", "Éducation & jeunesse"),
                            ("sante", "Santé"),
                            ("loisirs", "Loisirs"),
                            ("quartier", "Vie de quartier"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="thème",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="début")),
                ("end", models.DateTimeField(verbose_name="fin")),
                ("location", models.CharField(max_length=255, verbose_name="lieu")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public (visible par tous)"),
                            ("network", "Réseau (associations connectées uniquement)"),
                        ],
                        default="public",
                        max_length=10,
                        verbose_name="visibilité",
                    ),
                ),
                (
                    "volunteers_needed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 si vous ne cherchez pas de renfort.",
                        verbose_name="bénévoles recherchés",
                    ),
                ),
                (
                    "material_needs",
                    models.TextField(
                        blank=True,
                        help_text="Tables, barnums, sono… ce que vous aimeriez emprunter.",
                        verbose_name="besoins matériels",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="associations.association",
                        verbose_name="association organisatrice",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement",
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "commentaire",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("coorg", "Co-organise"),
                            ("participant", "Participe / tient un stand"),
                            ("support", "Apporte du soutien (matériel, bénévoles…)"),
                            ("interested", "Intéressée"),
                        ],
                        default="participant",
                        max_length=12,
                        verbose_name="type",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="associations.association",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "association"), name="unique_participation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteers",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteering",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "bénévole",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="unique_volunteer"
                    )
                ],
            },
        ),
    ]
