# Generated by Django 5.2.17 on 2026-10-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("associations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("volunteers", "Recherche de bénévoles"),
                            ("lend", "Prêt / don de matériel"),
                            ("borrow", "Recherche de matériel"),
                            ("partnership", "Appel à partenariat"),
                            ("space", "Salle / local"),
                            ("other", "Autre"),
                        ],
                        default="info",
                        max_length=12,
                        verbose_name="type d'annonce",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                ("body", models.TextField(verbose_name="contenu")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="clôturée"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="associations.association",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "annonce",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="réponse")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "association",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="associations.association",
                        verbose_name="au nom de",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="board.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "réponse",
                "ordering": ["created_at"],
            },
        ),
    ]
